#include "Jaguar2PhyTables.h"

#if defined(DEVOURER_HAVE_JAGUAR2_8821C)
#include "Hal8821c_PhyTables.h" /* generated: array_mp_8821c_* + _len externs */

namespace jaguar2 {
namespace {

/* rtl8821c (RTL8811CU / RTL8821CU) phydm MAC/BB/AGC/RF tables, generated by
 * tools/extract_8822c_phy_tables.py --chip 8821c into
 * hal/phydm/rtl8821c/Hal8821c_PhyTables. 1T1R: there is no radiob (path A only),
 * so radiob() returns an empty table and HalJaguar2 skips the path-B RF walk. */
class Phy8821cTables : public Jaguar2PhyTables {
public:
  Table mac_reg() const override {
    return {array_mp_8821c_mac_reg, array_mp_8821c_mac_reg_len};
  }
  Table phy_reg() const override {
    return {array_mp_8821c_phy_reg, array_mp_8821c_phy_reg_len};
  }
  Table agc_tab() const override {
    return {array_mp_8821c_agc_tab, array_mp_8821c_agc_tab_len};
  }
  Table radioa() const override {
    return {array_mp_8821c_radioa, array_mp_8821c_radioa_len};
  }
  Table radiob() const override { return {nullptr, 0}; } /* 1T1R: no path B */
};

} /* namespace */

std::unique_ptr<Jaguar2PhyTables> make_phy_8821c_tables() {
  return std::make_unique<Phy8821cTables>();
}

} /* namespace jaguar2 */
#endif /* DEVOURER_HAVE_JAGUAR2_8821C */
