#include "Jaguar2PhyTables.h"

#if defined(DEVOURER_HAVE_JAGUAR2_8822B)
#include "Hal8822b_PhyTables.h" /* generated: array_mp_8822b_* + _len externs */
#endif

namespace jaguar2 {

#if defined(DEVOURER_HAVE_JAGUAR2_8822B)
namespace {

/* rtl8822b (RTL8822BU) phydm MAC/BB/AGC/RF tables, generated by
 * tools/extract_8822c_phy_tables.py --chip 8822b into
 * hal/phydm/rtl8822b/Hal8822b_PhyTables. */
class Phy8822bTables : public Jaguar2PhyTables {
public:
  Table mac_reg() const override {
    return {array_mp_8822b_mac_reg, array_mp_8822b_mac_reg_len};
  }
  Table phy_reg() const override {
    return {array_mp_8822b_phy_reg, array_mp_8822b_phy_reg_len};
  }
  Table agc_tab() const override {
    return {array_mp_8822b_agc_tab, array_mp_8822b_agc_tab_len};
  }
  Table radioa() const override {
    return {array_mp_8822b_radioa, array_mp_8822b_radioa_len};
  }
  Table radiob() const override {
    return {array_mp_8822b_radiob, array_mp_8822b_radiob_len};
  }
};

} /* namespace */
#endif

#if defined(DEVOURER_HAVE_JAGUAR2_8821C)
/* Defined in Phy8821cTables.cpp. */
std::unique_ptr<Jaguar2PhyTables> make_phy_8821c_tables();
#endif

std::unique_ptr<Jaguar2PhyTables> make_jaguar2_phy_tables(ChipVariant variant) {
#if defined(DEVOURER_HAVE_JAGUAR2_8821C)
  if (variant == ChipVariant::C8821C)
    return make_phy_8821c_tables();
#endif
#if defined(DEVOURER_HAVE_JAGUAR2_8822B)
  (void)variant;
  return std::make_unique<Phy8822bTables>();
#else
  (void)variant;
  return nullptr;
#endif
}

} /* namespace jaguar2 */
