/* Auto-generated by tools/extract_8822c_phy_tables.py.
 * Source: libc0607/rtl88x2cu-20230728 (rtl8822c phydm). */

#ifndef HAL8822C_PHYTABLES_H
#define HAL8822C_PHYTABLES_H

#include "drv_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const u32 array_mp_8822c_agc_tab[];
extern const u32 array_mp_8822c_agc_tab_len;
extern const u32 array_mp_8822c_phy_reg[];
extern const u32 array_mp_8822c_phy_reg_len;
extern const u32 array_mp_8822c_phy_reg_pg[];
extern const u32 array_mp_8822c_phy_reg_pg_len;
extern const u32 array_mp_8822c_radioa[];
extern const u32 array_mp_8822c_radioa_len;
extern const u32 array_mp_8822c_radiob[];
extern const u32 array_mp_8822c_radiob_len;
extern const u32 array_mp_8822c_cal_init[];
extern const u32 array_mp_8822c_cal_init_len;

#ifdef __cplusplus
}
#endif

#endif /* HAL8822C_PHYTABLES_H */
