#ifndef HAL8822C_IQK_NCTL_H
#define HAL8822C_IQK_NCTL_H
#include "basic_types.h"

/* GENERATED by tools/extract_8822c_iqk_nctl.py from the rtl88x2cu
 * _iqk_nctl_8822c() — IQK NCTL microcode. {addr, mask, val}. */
struct iqk_nctl_write { u16 addr; u32 mask; u32 val; };
extern const struct iqk_nctl_write array_mp_8822c_iqk_nctl[];
extern const unsigned array_mp_8822c_iqk_nctl_len;

#endif
