/* Auto-generated by tools/extract_8822c_phy_tables.py.
 * Source: OpenHD/rtl88x2eu (rtl8822e phydm, FW v5.15.0.1-197). */

#ifndef HAL8822E_PHYTABLES_H
#define HAL8822E_PHYTABLES_H

#include "drv_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const u32 array_mp_8822e_agc_tab[];
extern const u32 array_mp_8822e_agc_tab_len;
extern const u32 array_mp_8822e_phy_reg[];
extern const u32 array_mp_8822e_phy_reg_len;
extern const u32 array_mp_8822e_phy_reg_pg[];
extern const u32 array_mp_8822e_phy_reg_pg_len;
extern const u32 array_mp_8822e_phy_reg_pg_type5[];
extern const u32 array_mp_8822e_phy_reg_pg_type5_len;
extern const u32 array_mp_8822e_radioa[];
extern const u32 array_mp_8822e_radioa_len;
extern const u32 array_mp_8822e_radiob[];
extern const u32 array_mp_8822e_radiob_len;
extern const u32 array_mp_8822e_cal_init[];
extern const u32 array_mp_8822e_cal_init_len;

#ifdef __cplusplus
}
#endif

#endif /* HAL8822E_PHYTABLES_H */
