#include "Jaguar3PhyTables.h"

#if defined(DEVOURER_HAVE_JAGUAR3_8822C)
#include "Hal8822c_PhyTables.h" /* array_mp_8822c_* + _len */
#endif

namespace jaguar3 {

#if defined(DEVOURER_HAVE_JAGUAR3_8822C)
namespace {

/* rtl8822c (RTL8812CU/8822CU) phydm BB/AGC/RF + cal-init tables, generated by
 * tools/extract_8822c_phy_tables.py into hal/phydm/rtl8822c/Hal8822c_PhyTables. */
class Phy8822cTables : public Jaguar3PhyTables {
public:
  Table phy_reg() const override {
    return {array_mp_8822c_phy_reg, array_mp_8822c_phy_reg_len};
  }
  Table agc_tab() const override {
    return {array_mp_8822c_agc_tab, array_mp_8822c_agc_tab_len};
  }
  Table radioa() const override {
    return {array_mp_8822c_radioa, array_mp_8822c_radioa_len};
  }
  Table radiob() const override {
    return {array_mp_8822c_radiob, array_mp_8822c_radiob_len};
  }
  Table cal_init() const override {
    return {array_mp_8822c_cal_init, array_mp_8822c_cal_init_len};
  }
};

} /* namespace */
#endif

#if defined(DEVOURER_HAVE_JAGUAR3_8822E)
/* Defined in Phy8822eTables.cpp. */
std::unique_ptr<Jaguar3PhyTables> make_phy_8822e_tables();
#endif

std::unique_ptr<Jaguar3PhyTables> make_jaguar3_phy_tables(ChipVariant variant) {
#if defined(DEVOURER_HAVE_JAGUAR3_8822E)
  if (variant == ChipVariant::C8822E)
    return make_phy_8822e_tables();
#endif
#if defined(DEVOURER_HAVE_JAGUAR3_8822C)
  return std::make_unique<Phy8822cTables>();
#else
  (void)variant;
  return nullptr;
#endif
}

} /* namespace jaguar3 */
