#include "Jaguar3PhyTables.h"

#include "Hal8822e_PhyTables.h" /* array_mp_8822e_* + _len */

namespace jaguar3 {

namespace {

/* rtl8822e (RTL8812EU/8822EU) phydm BB/AGC/RF + cal-init tables, generated by
 * tools/extract_8822c_phy_tables.py --chip 8822e into
 * hal/phydm/rtl8822e/Hal8822e_PhyTables. Same walker + apply sequence as 8822c;
 * only this data differs. */
class Phy8822eTables : public Jaguar3PhyTables {
public:
  Table phy_reg() const override {
    return {array_mp_8822e_phy_reg, array_mp_8822e_phy_reg_len};
  }
  Table agc_tab() const override {
    return {array_mp_8822e_agc_tab, array_mp_8822e_agc_tab_len};
  }
  Table radioa() const override {
    return {array_mp_8822e_radioa, array_mp_8822e_radioa_len};
  }
  Table radiob() const override {
    return {array_mp_8822e_radiob, array_mp_8822e_radiob_len};
  }
  Table cal_init() const override {
    return {array_mp_8822e_cal_init, array_mp_8822e_cal_init_len};
  }
};

} /* namespace */

/* Internal maker, called by the dispatcher in Phy8822cTables.cpp. */
std::unique_ptr<Jaguar3PhyTables> make_phy_8822e_tables() {
  return std::make_unique<Phy8822eTables>();
}

} /* namespace jaguar3 */
