/* Auto-generated by tools/extract_8822c_phy_tables.py.
 * Source: OpenHD/rtl88x2bu (rtl8822b phydm). */

#ifndef HAL8822B_PHYTABLES_H
#define HAL8822B_PHYTABLES_H

#include "drv_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const u32 array_mp_8822b_agc_tab[];
extern const u32 array_mp_8822b_agc_tab_len;
extern const u32 array_mp_8822b_phy_reg[];
extern const u32 array_mp_8822b_phy_reg_len;
extern const u32 array_mp_8822b_phy_reg_pg[];
extern const u32 array_mp_8822b_phy_reg_pg_len;
extern const u32 array_mp_8822b_phy_reg_pg_type12[];
extern const u32 array_mp_8822b_phy_reg_pg_type12_len;
extern const u32 array_mp_8822b_phy_reg_pg_type15[];
extern const u32 array_mp_8822b_phy_reg_pg_type15_len;
extern const u32 array_mp_8822b_phy_reg_pg_type16[];
extern const u32 array_mp_8822b_phy_reg_pg_type16_len;
extern const u32 array_mp_8822b_phy_reg_pg_type17[];
extern const u32 array_mp_8822b_phy_reg_pg_type17_len;
extern const u32 array_mp_8822b_phy_reg_pg_type18[];
extern const u32 array_mp_8822b_phy_reg_pg_type18_len;
extern const u32 array_mp_8822b_phy_reg_pg_type19[];
extern const u32 array_mp_8822b_phy_reg_pg_type19_len;
extern const u32 array_mp_8822b_phy_reg_pg_type2[];
extern const u32 array_mp_8822b_phy_reg_pg_type2_len;
extern const u32 array_mp_8822b_phy_reg_pg_type3[];
extern const u32 array_mp_8822b_phy_reg_pg_type3_len;
extern const u32 array_mp_8822b_phy_reg_pg_type4[];
extern const u32 array_mp_8822b_phy_reg_pg_type4_len;
extern const u32 array_mp_8822b_phy_reg_pg_type5[];
extern const u32 array_mp_8822b_phy_reg_pg_type5_len;
extern const u32 array_mp_8822b_mac_reg[];
extern const u32 array_mp_8822b_mac_reg_len;
extern const u32 array_mp_8822b_radioa[];
extern const u32 array_mp_8822b_radioa_len;
extern const u32 array_mp_8822b_radiob[];
extern const u32 array_mp_8822b_radiob_len;

#ifdef __cplusplus
}
#endif

#endif /* HAL8822B_PHYTABLES_H */
