/* Auto-generated by tools/extract_8822c_phy_tables.py.
 * Source: morrownr/8821cu-20210916 (rtl8821c phydm, FW v5.12.0.4). */

#ifndef HAL8821C_PHYTABLES_H
#define HAL8821C_PHYTABLES_H

#include "drv_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const u32 array_mp_8821c_agc_tab[];
extern const u32 array_mp_8821c_agc_tab_len;
extern const u32 array_mp_8821c_agc_tab_diff_wlg[];
extern const u32 array_mp_8821c_agc_tab_diff_wlg_len;
extern const u32 array_mp_8821c_agc_tab_diff_btg[];
extern const u32 array_mp_8821c_agc_tab_diff_btg_len;
extern const u32 array_mp_8821c_phy_reg[];
extern const u32 array_mp_8821c_phy_reg_len;
extern const u32 array_mp_8821c_phy_reg_mp[];
extern const u32 array_mp_8821c_phy_reg_mp_len;
extern const u32 array_mp_8821c_phy_reg_pg[];
extern const u32 array_mp_8821c_phy_reg_pg_len;
extern const u32 array_mp_8821c_phy_reg_pg_type0x28[];
extern const u32 array_mp_8821c_phy_reg_pg_type0x28_len;
extern const u32 array_mp_8821c_mac_reg[];
extern const u32 array_mp_8821c_mac_reg_len;
extern const u32 array_mp_8821c_radioa[];
extern const u32 array_mp_8821c_radioa_len;

#ifdef __cplusplus
}
#endif

#endif /* HAL8821C_PHYTABLES_H */
