#!/usr/bin/env python3
"""Generate the RTL8822C IQK NCTL microcode table from the vendor source.

_iqk_nctl_8822c() in hal/phydm/halrf/rtl8822c/halrf_iqk_8822c.c is 1809 flat BB
register writes (odm_write_4byte / odm_set_bb_reg) with no control flow — the
IQK calibration-engine config loaded into the 0x1B00 NCTL block before the cal
feedback loops run. Rather than hand-transcribe it, extract it here into a
{addr, mask, val} table walked by the ported IQK driver.

Mirrors tools/extract_8822c_phy_tables.py: edit this generator, not the output.

  python3 tools/extract_8822c_iqk_nctl.py reference/rtl88x2cu
"""
import re
import sys
from pathlib import Path

SRC = "hal/phydm/halrf/rtl8822c/halrf_iqk_8822c.c"
FUNC = "_iqk_nctl_8822c"
OUT_C = "hal/phydm/rtl8822c/Hal8822c_IqkNctl.c"
OUT_H = "hal/phydm/rtl8822c/Hal8822c_IqkNctl.h"

W4 = re.compile(r"odm_write_4byte\(dm,\s*([0-9a-fA-Fx]+),\s*([0-9a-fA-Fx]+)\)")
SETBB = re.compile(r"odm_set_bb_reg\(dm,\s*([0-9a-fA-Fx]+),\s*(.+?),\s*([0-9a-fA-Fx]+)\)")
BIT = re.compile(r"BIT\((\d+)\)")


def eval_mask(expr: str) -> int:
    """Evaluate a mask expression: BIT(a)|BIT(b)|0xNN | MASKDWORD."""
    expr = expr.strip()
    if expr == "MASKDWORD":
        return 0xFFFFFFFF
    expr = BIT.sub(lambda m: str(1 << int(m.group(1))), expr)
    val = 0
    for tok in expr.split("|"):
        tok = tok.strip()
        if not tok:
            continue
        val |= int(tok, 0)
    return val


def extract(root: Path):
    text = (root / SRC).read_text(errors="ignore")
    # isolate the function body
    start = text.index("void\n" + FUNC) if ("void\n" + FUNC) in text else text.index(FUNC)
    body = text[start:]
    depth = 0
    began = False
    end = len(body)
    for i, c in enumerate(body):
        if c == "{":
            depth += 1
            began = True
        elif c == "}":
            depth -= 1
            if began and depth == 0:
                end = i
                break
    body = body[:end]

    rows = []
    for line in body.splitlines():
        line = line.split("//")[0]
        m = W4.search(line)
        if m:
            rows.append((int(m.group(1), 16), 0xFFFFFFFF, int(m.group(2), 16)))
            continue
        m = SETBB.search(line)
        if m:
            rows.append((int(m.group(1), 16), eval_mask(m.group(2)), int(m.group(3), 16)))
    return rows


def main():
    root = Path(sys.argv[1] if len(sys.argv) > 1 else "reference/rtl88x2cu")
    rows = extract(root)
    repo = Path(__file__).resolve().parent.parent
    hdr = (repo / OUT_H)
    src = (repo / OUT_C)
    hdr.write_text(
        "#ifndef HAL8822C_IQK_NCTL_H\n#define HAL8822C_IQK_NCTL_H\n"
        "#include \"basic_types.h\"\n\n"
        "/* GENERATED by tools/extract_8822c_iqk_nctl.py from the rtl88x2cu\n"
        " * _iqk_nctl_8822c() — IQK NCTL microcode. {addr, mask, val}. */\n"
        "struct iqk_nctl_write { u16 addr; u32 mask; u32 val; };\n"
        "extern const struct iqk_nctl_write array_mp_8822c_iqk_nctl[];\n"
        "extern const unsigned array_mp_8822c_iqk_nctl_len;\n\n"
        "#endif\n")
    lines = ["#include \"Hal8822c_IqkNctl.h\"\n",
             "const struct iqk_nctl_write array_mp_8822c_iqk_nctl[] = {"]
    for a, m, v in rows:
        lines.append(f"\t{{0x{a:04X}, 0x{m:08X}, 0x{v:08X}}},")
    lines.append("};")
    lines.append("const unsigned array_mp_8822c_iqk_nctl_len = "
                 "sizeof(array_mp_8822c_iqk_nctl) / sizeof(array_mp_8822c_iqk_nctl[0]);\n")
    src.write_text("\n".join(lines))
    print(f"wrote {len(rows)} IQK NCTL writes -> {OUT_C}")


if __name__ == "__main__":
    main()
