#!/usr/bin/env python3
"""Extract pinned RTL8733B MAC/BB/AGC/RF/RFK-init parameter arrays.

The generated file retains the vendor condition opcodes. Selection happens in
the production PHY table walker, where cut/package/interface/RFE inputs can be
logged and tested independently of this mechanical extraction step.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import struct
from pathlib import Path

UPSTREAM = "libc0607/rtl8733bu-20230626 commit 9e5f684"
DEFAULT_ROOT = "reference/rtl8733bu-20230626"
SUBMODULE_HINT = (
    f"{DEFAULT_ROOT} is a pinned git submodule ({UPSTREAM}); fetch it with\n"
    f"  git submodule update --init {DEFAULT_ROOT}"
)
OUTPUT_C = "hal/hal8733b_tables.c"
OUTPUT_H = "hal/hal8733b_tables.h"

SOURCES = {
    "mac": (
        "hal/phydm/rtl8733b/halhwimg8733b_mac.c",
        "526897103f92972fbff53ea4dc2fb210185de535948cb1d0fd62019bdf3a4a12",
    ),
    "bb": (
        "hal/phydm/rtl8733b/halhwimg8733b_bb.c",
        "b2a379b7a202f05eece240f56af6b21664ea689d1f72987c78d4c4d7d6ef107d",
    ),
    "rf": (
        "hal/phydm/halrf/rtl8733b/halhwimg8733b_rf.c",
        "4b90641be80f97fcc0b76f921c94647dae1af15f59720005413b56ff3be69113",
    ),
    "rfk": (
        "hal/phydm/halrf/rtl8733b/halrf_rfk_init_8733b.c",
        "fc113be536c22b28a1134f4ed8b20d37bfb0157c1f761e63d6dc30aeccc00257",
    ),
}

# name: (source key, u32 count, SHA-256 of little-endian u32 stream)
ARRAYS = {
    "array_mp_8733b_mac_reg": (
        "mac", 36, "e4c1ae16790ede591a701b8e4df490ee9adfbb4aeb645f6f82dd2d5709b1454d"
    ),
    "array_mp_8733b_agc_tab": (
        "bb", 1668, "c74289e6788272bead0afd1ee4549834e639d3ddedd36af3689dc7aadca0caae"
    ),
    "array_mp_8733b_phy_reg": (
        "bb", 2068, "5e7498d7d3e7a99a3e160e86362aeb6c07a919c5185407ae86fe03e7a5028e67"
    ),
    "array_mp_8733b_phy_reg_pg": (
        "bb", 84, "a8861b3236346adc7dbd4a1d31d000ae5ac4a337dd2e9080f47d6d007caf2210"
    ),
    "array_mp_8733b_radioa": (
        "rf", 170, "da7bdfafa60a25196513e0b8df8da250a5958d2ebbc6ff0d65bdb2e53647fb42"
    ),
    "array_mp_8733b_radiob": (
        "rf", 64, "22ca079b882507903215c7213474b1e7be1f17141ef0fac5f05764afdfa5e371"
    ),
    "array_mp_8733b_cal_init": (
        "rfk", 2298, "c4037c479bfa15d1ddb1073195026c212484439505ad0fdbd68d44b5e07b2244"
    ),
}


def strip_comments(body: str) -> str:
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    return re.sub(r"//[^\n]*", "", body)


def extract_array(text: str, name: str) -> list[int]:
    match = re.search(rf"(?:const\s+)?u32\s+{name}\[\]\s*=\s*\{{", text)
    if not match:
        raise SystemExit(f"could not find {name}[]")
    end = text.find("};", match.end())
    if end < 0:
        raise SystemExit(f"unterminated {name}[]")
    body = strip_comments(text[match.end():end])
    tokens = re.findall(r"0x[0-9a-fA-F]+|\b\d+\b", body)
    return [int(token, 0) for token in tokens]


def value_hash(values: list[int]) -> str:
    raw = b"".join(struct.pack("<I", value) for value in values)
    return hashlib.sha256(raw).hexdigest()


def load(source_root: Path) -> dict[str, list[int]]:
    texts: dict[str, str] = {}
    for key, (relative, expected_hash) in SOURCES.items():
        path = source_root / relative
        if not path.exists():
            raise SystemExit(f"missing input: {path}\n{SUBMODULE_HINT}")
        source = path.read_bytes()
        actual_hash = hashlib.sha256(source).hexdigest()
        if actual_hash != expected_hash:
            raise SystemExit(
                f"unexpected {relative} SHA-256: {actual_hash}; "
                f"expected {expected_hash}"
            )
        texts[key] = source.decode("utf-8")

    result: dict[str, list[int]] = {}
    for name, (source_key, count, expected_hash) in ARRAYS.items():
        values = extract_array(texts[source_key], name)
        actual_hash = value_hash(values)
        if len(values) != count or actual_hash != expected_hash:
            raise SystemExit(
                f"unexpected {name}: count={len(values)} sha256={actual_hash}; "
                f"expected count={count} sha256={expected_hash}"
            )
        result[name] = values
    return result


def render_c(arrays: dict[str, list[int]]) -> str:
    hashes = "\n".join(
        f" * {key} source SHA-256: {source_hash}"
        for key, (_, source_hash) in SOURCES.items()
    )
    parts = [
        "/* Auto-extracted RTL8733B parameter tables.\n"
        f" * Source: {UPSTREAM}.\n{hashes}\n"
        " * Generated by tools/extract_8733b_tables.py. Vendor source files\n"
        " * carry GPL-2.0 notices; the repository has a GPL-3.0 LICENSE. */\n"
        '#include "hal8733b_tables.h"\n\n'
    ]
    for name, values in arrays.items():
        parts.append(
            f"/* {len(values)} u32; LE-stream SHA-256 {value_hash(values)} */\n"
            f"const uint32_t {name}[] = {{\n"
        )
        for offset in range(0, len(values), 4):
            row = values[offset:offset + 4]
            parts.append("    " + ", ".join(f"0x{value:08x}u" for value in row) + ",\n")
        parts.append(
            "};\n"
            f"const size_t {name}_len = sizeof({name}) / sizeof({name}[0]);\n\n"
        )
    return "".join(parts).rstrip() + "\n"


def render_h() -> str:
    declarations = "".join(
        f"extern const uint32_t {name}[];\nextern const size_t {name}_len;\n"
        for name in ARRAYS
    )
    return (
        "/* Auto-extracted RTL8733B parameter tables. See hal8733b_tables.c. */\n"
        "#ifndef HAL8733B_TABLES_H\n#define HAL8733B_TABLES_H\n"
        "#include <stddef.h>\n#include <stdint.h>\n"
        "#ifdef __cplusplus\nextern \"C\" {\n#endif\n"
        + declarations
        + "#ifdef __cplusplus\n}\n#endif\n#endif /* HAL8733B_TABLES_H */\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    root = Path(__file__).resolve().parent.parent
    source_root = args.source_root or root / DEFAULT_ROOT
    arrays = load(source_root)
    outputs = {OUTPUT_C: render_c(arrays), OUTPUT_H: render_h()}
    # Explicit encoding + newline="": the generated files are byte-defined
    # artifacts, so --check must compare bytes identically on every platform.
    # Without newline="", Windows would write CRLF on generate and translate it
    # back on read, making the round-trip pass while the checked-in file differs.
    if args.check:
        stale = [
            path for path, expected in outputs.items()
            if not (root / path).exists()
            or (root / path).read_text(encoding="utf-8", newline="") != expected
        ]
        if stale:
            raise SystemExit("stale generated output: " + ", ".join(stale))
        verb = "verified"
    else:
        for path, output in outputs.items():
            (root / path).write_text(output, encoding="utf-8", newline="")
        verb = "wrote"
    summary = ", ".join(f"{name}={len(values)}" for name, values in arrays.items())
    print(f"{verb} {OUTPUT_C} and {OUTPUT_H}: {summary}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
