#!/usr/bin/env python3
"""Extract const u32 array_mp_8814a_*[] data blocks from upstream
aircrack-ng/rtl8814au phydm tables, dropping the phydm parser/check_positive
machinery that devourer doesn't link.

Input: hal/phydm/rtl8814a/halhwimg8814a_{bb,mac}.c (verbatim from upstream
v5.8.5.1).
Output: hal/phydm/rtl8814a/Hal8814_PhyTables.{c,h}
        Hal8814_PhyTables.c — the array bodies only, with a *_len companion.
        Hal8814_PhyTables.h — extern declarations consumed by src/PhyTableLoader.

The runtime parser (matching upstream's `odm_read_and_config_mp_8814a_*` state
machine) lives in src/PhyTableLoader.{h,cpp}.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

UPSTREAM_TAG = "aircrack-ng/rtl8814au v5.8.5.1"
INPUT_FILES = [
    "hal/phydm/rtl8814a/halhwimg8814a_bb.c",
    "hal/phydm/rtl8814a/halhwimg8814a_mac.c",
    "hal/phydm/halrf/rtl8814a/halhwimg8814a_rf.c",
]
OUTPUT_C = "hal/phydm/rtl8814a/Hal8814_PhyTables.c"
OUTPUT_H = "hal/phydm/rtl8814a/Hal8814_PhyTables.h"

ARRAY_RE = re.compile(r"^const\s+u32\s+(array_mp_8814a_\w+)\s*\[\s*\]\s*=\s*\{\s*$")


def extract(repo_root: Path) -> tuple[list[tuple[str, list[str]]], list[str]]:
    """Return (arrays, source_blames). Each array is (name, body_lines)."""
    arrays: list[tuple[str, list[str]]] = []
    blames: list[str] = []
    for rel in INPUT_FILES:
        path = repo_root / rel
        if not path.exists():
            sys.exit(f"missing input: {rel}")
        lines = path.read_text().splitlines()
        in_array: str | None = None
        body: list[str] = []
        for line in lines:
            if in_array is None:
                m = ARRAY_RE.match(line)
                if m:
                    in_array = m.group(1)
                    body = []
                continue
            if line.strip().startswith("};"):
                arrays.append((in_array, body))
                blames.append(f"{rel}::{in_array} ({len(body)} lines)")
                in_array = None
                body = []
                continue
            body.append(line)
    return arrays, blames


def emit_c(arrays: list[tuple[str, list[str]]], blames: list[str]) -> str:
    parts: list[str] = []
    parts.append("/* Auto-generated by tools/extract_8814a_phy_tables.py.")
    parts.append(f" * Source: {UPSTREAM_TAG}.")
    parts.append(" * Extracted arrays:")
    for b in blames:
        parts.append(f" *   {b}")
    parts.append(" * Edit the source files upstream and re-run the extractor; do not hand-edit. */")
    parts.append("")
    parts.append('#include "drv_types.h"')
    parts.append('#include "Hal8814_PhyTables.h"')
    parts.append("")
    for name, body in arrays:
        parts.append(f"const u32 {name}[] = {{")
        parts.extend(body)
        parts.append("};")
        parts.append(
            f"const u32 {name}_len = sizeof({name}) / sizeof(u32);"
        )
        parts.append("")
    return "\n".join(parts) + "\n"


def emit_h(arrays: list[tuple[str, list[str]]]) -> str:
    parts: list[str] = []
    parts.append("/* Auto-generated by tools/extract_8814a_phy_tables.py.")
    parts.append(f" * Source: {UPSTREAM_TAG}. */")
    parts.append("")
    parts.append("#ifndef HAL8814_PHYTABLES_H")
    parts.append("#define HAL8814_PHYTABLES_H")
    parts.append("")
    parts.append('#include "drv_types.h"')
    parts.append("")
    parts.append("#ifdef __cplusplus")
    parts.append('extern "C" {')
    parts.append("#endif")
    parts.append("")
    for name, _ in arrays:
        parts.append(f"extern const u32 {name}[];")
        parts.append(f"extern const u32 {name}_len;")
    parts.append("")
    parts.append("#ifdef __cplusplus")
    parts.append("}")
    parts.append("#endif")
    parts.append("")
    parts.append("#endif /* HAL8814_PHYTABLES_H */")
    return "\n".join(parts) + "\n"


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    arrays, blames = extract(repo_root)
    if not arrays:
        sys.exit("no arrays found — extraction regex probably needs an update")
    (repo_root / OUTPUT_C).write_text(emit_c(arrays, blames))
    (repo_root / OUTPUT_H).write_text(emit_h(arrays))
    print(f"wrote {OUTPUT_C} ({sum(len(b) for _, b in arrays)} array body lines, {len(arrays)} arrays)")
    print(f"wrote {OUTPUT_H}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
