#!/usr/bin/env python3
"""Extract the RTL8822B TX-power regulatory limit (txpwr_lmt) tables into a
compact C lookup header.

Source: reference/rtl88x2bu/hal/phydm/halrf/rtl8822b/halhwimg8822b_rf.c
  const char *array_mp_8822b_txpwr_lmt[]        (base / default rfe_type)
  const char *array_mp_8822b_txpwr_lmt_type3[]  (rfe_type 3 — the Archer T3U)

Each logical row is 7 strings: regd, band, bw, section, ntx, channel, limit.
We collapse the per-regdomain rows to the WORLDWIDE MINIMUM (min across FCC/ETSI/
MKK/...) per (band, bw, section, ntx, channel) — the always-regulatory-compliant
value, which is what a userspace monitor/injection tool should clamp to absent a
country configuration.

Output: hal/phydm/rtl8822b/Hal8822b_TxpwrLmt.h (header-only, static const arrays
+ an inline lookup). Edit this generator, not the output.

Usage: python3 tools/extract_8822b_txpwr_lmt.py
"""
import re
import sys
from pathlib import Path

SRC = "reference/rtl88x2bu/hal/phydm/halrf/rtl8822b/halhwimg8822b_rf.c"
OUT = "hal/phydm/rtl8822b/Hal8822b_TxpwrLmt.h"
GUARD = "HAL8822B_TXPWRLMT_H"

BAND = {"2.4G": 0, "5G": 1}
BW = {"20M": 0, "40M": 1, "80M": 2, "160M": 3}
SEC = {"CCK": 0, "OFDM": 1, "HT": 2, "VHT": 3}
NTX = {"1T": 1, "2T": 2, "3T": 3, "4T": 4}


def extract_array(text: str, name: str) -> list[str]:
    m = re.search(rf"const char \*{re.escape(name)}\[\]\s*=\s*\{{(.*?)\}};",
                  text, re.S)
    if not m:
        sys.exit(f"array {name} not found in source")
    return re.findall(r'"([^"]*)"', m.group(1))


def ww_min(strings: list[str]) -> dict:
    """Rows of 7 -> {(band,bw,sec,ntx,ch): min_limit}."""
    if len(strings) % 7:
        sys.exit(f"row count {len(strings)} not a multiple of 7")
    out: dict = {}
    for i in range(0, len(strings), 7):
        regd, band, bw, sec, ntx, ch, lmt = (s.strip() for s in strings[i:i + 7])
        if band not in BAND or bw not in BW or sec not in SEC or ntx not in NTX:
            continue
        try:
            key = (BAND[band], BW[bw], SEC[sec], NTX[ntx], int(ch))
            val = int(lmt)  # 63 == "no limit" (NA in some tables shows as 63)
        except ValueError:
            continue
        out[key] = min(out.get(key, 127), val)
    return out


def emit(name: str, table: dict) -> str:
    rows = sorted(table.items())
    p = [f"static const struct txpwr_lmt_ent {name}[] = {{"]
    for (band, bw, sec, ntx, ch), lmt in rows:
        p.append(f"  {{{band}, {bw}, {sec}, {ntx}, {ch}, {lmt}}},")
    p.append("};")
    p.append(f"static const unsigned {name}_len = "
             f"sizeof({name}) / sizeof({name}[0]);")
    return "\n".join(p)


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    text = (root / SRC).read_text()
    base = ww_min(extract_array(text, "array_mp_8822b_txpwr_lmt"))
    type3 = ww_min(extract_array(text, "array_mp_8822b_txpwr_lmt_type3"))

    hdr = [
        f"/* Auto-generated by tools/extract_8822b_txpwr_lmt.py — do not hand-edit.",
        " * RTL8822B txpwr_lmt (regulatory TX-power limit), worldwide-min per cell.",
        " * band 0=2.4G/1=5G; bw 0=20/1=40/2=80; sec 0=CCK/1=OFDM/2=HT/3=VHT;",
        " * ntx 1..4; ch = channel; lmt in TXAGC index units (63 = no limit). */",
        f"#ifndef {GUARD}",
        f"#define {GUARD}",
        "",
        "#include <stdint.h>",
        "",
        "struct txpwr_lmt_ent {",
        "  uint8_t band, bw, sec, ntx, ch;",
        "  int8_t  lmt;",
        "};",
        "",
        emit("mp_8822b_txpwr_lmt_ww", base),
        "",
        emit("mp_8822b_txpwr_lmt_type3_ww", type3),
        "",
        "/* Lookup the WW-min limit for (rfe_type, band, bw, sec, ntx, ch). Falls",
        " * back to the nearest channel in the same (band,bw,sec,ntx), then to 63",
        " * (no limit) if the cell is absent. rfe_type 3 uses the type3 table; all",
        " * others use the base table (matches phydm_hwconfig.c dispatch). */",
        "static inline int hal8822b_txpwr_lmt(uint8_t rfe_type, uint8_t band,",
        "                                     uint8_t bw, uint8_t sec, uint8_t ntx,",
        "                                     uint8_t ch) {",
        "  const struct txpwr_lmt_ent *t = mp_8822b_txpwr_lmt_ww;",
        "  unsigned n = mp_8822b_txpwr_lmt_ww_len;",
        "  if (rfe_type == 3) { t = mp_8822b_txpwr_lmt_type3_ww;",
        "                       n = mp_8822b_txpwr_lmt_type3_ww_len; }",
        "  int best = 63, best_d = 255;",
        "  for (unsigned i = 0; i < n; i++) {",
        "    if (t[i].band != band || t[i].bw != bw || t[i].sec != sec ||",
        "        t[i].ntx != ntx)",
        "      continue;",
        "    if (t[i].ch == ch) return t[i].lmt;",
        "    int d = t[i].ch > ch ? t[i].ch - ch : ch - t[i].ch;",
        "    if (d < best_d) { best_d = d; best = t[i].lmt; }",
        "  }",
        "  return best;",
        "}",
        "",
        f"#endif /* {GUARD} */",
        "",
    ]
    (root / OUT).write_text("\n".join(hdr))
    print(f"wrote {OUT}: base={len(base)} cells, type3={len(type3)} cells")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
