#!/usr/bin/env python3
"""Extract const u32 array_mp_8822c_*[] data blocks from upstream Realtek
rtl8822c phydm tables, dropping the phydm parser/check_positive machinery that
devourer doesn't link. Mirror of tools/extract_8814a_phy_tables.py for the
Jaguar3 family.

WORK IN PROGRESS (M1): the INPUT_FILES below must first be vendored from the
rtl88x2eu / rtl88x2cu tree (hal/phydm/rtl8822c/...) into this repo. Until then
this generator has nothing to read and exits with "missing input".

Input:  hal/phydm/rtl8822c/halhwimg8822c_{bb,mac}.c  (+ halrf rf table)
Output: hal/phydm/rtl8822c/Hal8822c_PhyTables.{c,h}

The runtime parser is the SAME src/PhyTableLoader — the Jaguar3 halhwimg tables
use the same opcode/check_positive conditional encoding as Jaguar1, so no new
walker is needed (only the per-chip context: cut_version, rfe_type, ...).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

UPSTREAM_TAG = "libc0607/rtl88x2cu-20230728 (rtl8822c phydm)"
# NB: unlike Jaguar1, there is NO phydm MAC table for Jaguar3 — MAC register init
# is done by HalMAC. So only the BB (agc_tab + phy_reg + phy_reg_pg) and RF
# (radioa/radiob) tables are extracted here.
INPUT_FILES = [
    "hal/phydm/rtl8822c/halhwimg8822c_bb.c",
    "hal/phydm/halrf/rtl8822c/halhwimg8822c_rf.c",
]
OUTPUT_C = "hal/phydm/rtl8822c/Hal8822c_PhyTables.c"
OUTPUT_H = "hal/phydm/rtl8822c/Hal8822c_PhyTables.h"

ARRAY_RE = re.compile(r"^const\s+u32\s+(array_mp_8822c_\w+)\s*\[\s*\]\s*=\s*\{\s*$")


def extract(repo_root: Path) -> tuple[list[tuple[str, list[str]]], list[str]]:
    arrays: list[tuple[str, list[str]]] = []
    blames: list[str] = []
    for rel in INPUT_FILES:
        path = repo_root / rel
        if not path.exists():
            sys.exit(
                f"missing input: {rel}\n"
                "  -> M1 must vendor the rtl8822c phydm sources first "
                "(see docs/jaguar3-bringup.md)."
            )
        lines = path.read_text().splitlines()
        in_array: str | None = None
        body: list[str] = []
        for line in lines:
            if in_array is None:
                m = ARRAY_RE.match(line)
                if m:
                    in_array = m.group(1)
                    body = []
                continue
            if line.strip().startswith("};"):
                arrays.append((in_array, body))
                blames.append(f"{rel}::{in_array} ({len(body)} lines)")
                in_array = None
                body = []
                continue
            body.append(line)
    return arrays, blames


def emit_c(arrays: list[tuple[str, list[str]]], blames: list[str]) -> str:
    parts: list[str] = []
    parts.append("/* Auto-generated by tools/extract_8822c_phy_tables.py.")
    parts.append(f" * Source: {UPSTREAM_TAG}.")
    parts.append(" * Extracted arrays:")
    for b in blames:
        parts.append(f" *   {b}")
    parts.append(" * Edit the source files upstream and re-run; do not hand-edit. */")
    parts.append("")
    parts.append('#include "drv_types.h"')
    parts.append('#include "Hal8822c_PhyTables.h"')
    parts.append("")
    for name, body in arrays:
        parts.append(f"const u32 {name}[] = {{")
        parts.extend(body)
        parts.append("};")
        parts.append(f"const u32 {name}_len = sizeof({name}) / sizeof(u32);")
        parts.append("")
    return "\n".join(parts) + "\n"


def emit_h(arrays: list[tuple[str, list[str]]]) -> str:
    parts: list[str] = []
    parts.append("/* Auto-generated by tools/extract_8822c_phy_tables.py.")
    parts.append(f" * Source: {UPSTREAM_TAG}. */")
    parts.append("")
    parts.append("#ifndef HAL8822C_PHYTABLES_H")
    parts.append("#define HAL8822C_PHYTABLES_H")
    parts.append("")
    parts.append('#include "drv_types.h"')
    parts.append("")
    parts.append("#ifdef __cplusplus")
    parts.append('extern "C" {')
    parts.append("#endif")
    parts.append("")
    for name, _ in arrays:
        parts.append(f"extern const u32 {name}[];")
        parts.append(f"extern const u32 {name}_len;")
    parts.append("")
    parts.append("#ifdef __cplusplus")
    parts.append("}")
    parts.append("#endif")
    parts.append("")
    parts.append("#endif /* HAL8822C_PHYTABLES_H */")
    return "\n".join(parts) + "\n"


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    arrays, blames = extract(repo_root)
    if not arrays:
        sys.exit("no arrays found — extraction regex probably needs an update")
    (repo_root / OUTPUT_C).write_text(emit_c(arrays, blames))
    (repo_root / OUTPUT_H).write_text(emit_h(arrays))
    print(f"wrote {OUTPUT_C} ({sum(len(b) for _, b in arrays)} body lines, "
          f"{len(arrays)} arrays)")
    print(f"wrote {OUTPUT_H}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
