#!/usr/bin/env python3
"""Extract the RTL8821C TX-power regulatory limit (txpwr_lmt) table into a compact
C lookup header.

Source: reference/8821cu/hal/phydm/halrf/rtl8821c/halhwimg8821c_rf.c
  const struct txpwr_lmt_t_8821c array_mp_8821c_txpwr_lmt[] = {
    {PW_LMT_REGU_x, PW_LMT_BAND_y, PW_LMT_BW_z, PW_LMT_RS_w, PW_LMT_PH_nT, ch, val},
    ...
  };

Unlike the 8822B table (arrays of strings), the 8821C table is a packed struct
with named enum constants. We collapse the per-regdomain rows to the WORLDWIDE
MINIMUM (min across FCC/ETSI/MKK/...) per (band, bw, section, ntx, channel) — the
always-regulatory-compliant value a userspace monitor/injection tool should clamp
to absent a country configuration.

Output: hal/phydm/rtl8821c/Hal8821c_TxpwrLmt.h (header-only, static const array +
inline lookup hal8821c_txpwr_lmt). Edit this generator, not the output.

Usage: python3 tools/extract_8821c_txpwr_lmt.py
"""
import re
import sys
from pathlib import Path

SRC = "reference/8821cu/hal/phydm/halrf/rtl8821c/halhwimg8821c_rf.c"
OUT = "hal/phydm/rtl8821c/Hal8821c_TxpwrLmt.h"
GUARD = "HAL8821C_TXPWRLMT_H"
ARRAY = "array_mp_8821c_txpwr_lmt"

# Map the vendor enum names to devourer's numeric convention (matches the
# hal8822b_txpwr_lmt lookup args): band 0=2.4G/1=5G; bw 0=20/1=40/2=80/3=160;
# sec 0=CCK/1=OFDM/2=HT/3=VHT; ntx 1..4.
BAND = {"PW_LMT_BAND_2_4G": 0, "PW_LMT_BAND_5G": 1}
BW = {"PW_LMT_BW_20M": 0, "PW_LMT_BW_40M": 1, "PW_LMT_BW_80M": 2, "PW_LMT_BW_160M": 3}
SEC = {"PW_LMT_RS_CCK": 0, "PW_LMT_RS_OFDM": 1, "PW_LMT_RS_HT": 2, "PW_LMT_RS_VHT": 3}
NTX = {"PW_LMT_PH_1T": 1, "PW_LMT_PH_2T": 2, "PW_LMT_PH_3T": 3, "PW_LMT_PH_4T": 4}

ENTRY = re.compile(
    r"\{\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*,"
    r"\s*(-?\d+)\s*,\s*(-?\d+)\s*\}"
)


def ww_min(text: str) -> dict:
    m = re.search(rf"{re.escape(ARRAY)}\[\]\s*=\s*\{{(.*?)\}};", text, re.S)
    if not m:
        sys.exit(f"array {ARRAY} not found in source")
    out: dict = {}
    for regd, band, bw, sec, ntx, ch, val in ENTRY.findall(m.group(1)):
        if band not in BAND or bw not in BW or sec not in SEC or ntx not in NTX:
            continue
        key = (BAND[band], BW[bw], SEC[sec], NTX[ntx], int(ch))
        out[key] = min(out.get(key, 127), int(val))
    if not out:
        sys.exit("no valid txpwr_lmt rows parsed — check enum name mappings")
    return out


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    table = ww_min((root / SRC).read_text())
    rows = sorted(table.items())

    p = [
        "/* Auto-generated by tools/extract_8821c_txpwr_lmt.py — do not hand-edit.",
        " * RTL8821C txpwr_lmt (regulatory TX-power limit), worldwide-min per cell.",
        " * band 0=2.4G/1=5G; bw 0=20/1=40/2=80; sec 0=CCK/1=OFDM/2=HT/3=VHT;",
        " * ntx 1..4; ch = channel; lmt in TXAGC index units (63 = no limit). */",
        f"#ifndef {GUARD}",
        f"#define {GUARD}",
        "",
        "#include <stdint.h>",
        "",
        "struct txpwr_lmt_ent_8821c {",
        "  uint8_t band, bw, sec, ntx, ch;",
        "  int8_t  lmt;",
        "};",
        "",
        "static const struct txpwr_lmt_ent_8821c mp_8821c_txpwr_lmt_ww[] = {",
    ]
    for (band, bw, sec, ntx, ch), lmt in rows:
        p.append(f"  {{{band}, {bw}, {sec}, {ntx}, {ch}, {lmt}}},")
    p += [
        "};",
        "static const unsigned mp_8821c_txpwr_lmt_ww_len =",
        "    sizeof(mp_8821c_txpwr_lmt_ww) / sizeof(mp_8821c_txpwr_lmt_ww[0]);",
        "",
        "/* WW-min limit for (band, bw, sec, ntx, ch): exact channel, else nearest",
        " * channel in the same (band,bw,sec,ntx), else 63 (no limit). */",
        "static inline int hal8821c_txpwr_lmt(uint8_t band, uint8_t bw,",
        "                                     uint8_t sec, uint8_t ntx,",
        "                                     uint8_t ch) {",
        "  const struct txpwr_lmt_ent_8821c *t = mp_8821c_txpwr_lmt_ww;",
        "  int best = 63, best_d = 255;",
        "  for (unsigned i = 0; i < mp_8821c_txpwr_lmt_ww_len; i++) {",
        "    if (t[i].band != band || t[i].bw != bw || t[i].sec != sec ||",
        "        t[i].ntx != ntx)",
        "      continue;",
        "    if (t[i].ch == ch) return t[i].lmt;",
        "    int d = t[i].ch > ch ? t[i].ch - ch : ch - t[i].ch;",
        "    if (d < best_d) { best_d = d; best = t[i].lmt; }",
        "  }",
        "  return best;",
        "}",
        "",
        f"#endif /* {GUARD} */",
        "",
    ]
    (root / OUT).write_text("\n".join(p))
    print(f"wrote {OUT}: {len(table)} cells from {len(ENTRY.findall(open(root/SRC).read()))} rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
