#!/usr/bin/env python3
"""Emit a binary URB script from a pcapng captured by tshark on usbmonN.

The output is consumed by tools/usbmon_replay (compiled C binary) which
replays each URB verbatim via USBDEVFS_SUBMITURB. The two-stage pipeline
lets the heavy pcap parsing live in Python (already implemented in
tools/usbmon_pcap_diff.py) while the kernel-facing replay stays in C
where the ioctl interface is direct.

What we emit:

  file header (12 bytes):
    char magic[4]     = "URBS"
    u32  version      = 1   (LE)
    u32  urb_count    (LE)

  per-URB record (24 + data_bytes bytes):
    u8  xfer_type     1=INTR, 2=CTRL, 3=BULK   (skip ISO; not used by Realtek)
    u8  ep_with_dir   bit 7 = IN, bits 3..0 = ep number
    u16 reserved
    u32 inter_urb_gap_us   time since previous SUBMIT (0 for first)
    u8  setup[8]      control setup packet; zero-filled for non-control
    u32 transfer_length   wire transfer size (for OUT: bytes to send; for
                           IN: bytes to expect/receive)
    u32 data_bytes    actual bytes following this header (0 for IN; equal
                       to transfer_length for OUT)
    u8  data[data_bytes]  OUT payload — IN URBs carry no on-disk data
                           because the data comes from the chip at replay
                           time

Only SUBMIT records are emitted. Completion events are generated by the
chip+kernel during replay — replaying them would make no sense.

Filtering: --busnum / --devnum restrict to a specific device. --skip-bulk-in
drops interrupt/bulk IN URBs that the kernel polls but the chip may not
strictly require for replay (use sparingly — IN URBs can be load-bearing if
the chip's state machine reacts to a C2H message the kernel reads).

Usage:
  sudo tshark -i usbmon4 -s 0 -w /tmp/k.pcapng    # capture kernel side
  # ... let modprobe 88XXau + airodump-ng run, then Ctrl-C tshark
  python3 tools/pcapng_to_urbscript.py /tmp/k.pcapng --busnum 4 --devnum 2 \\
      -o /tmp/k.urbs
  sudo ./build/usbmon_replay --device /dev/bus/usb/004/002 --urbs /tmp/k.urbs
"""

from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from usbmon_pcap_diff import (  # noqa: E402
    Urb,
    XFER_LETTER,
    read_urbs,
)

MAGIC = b"URBS"
VERSION = 1
HEADER_FMT = "<4sII"
HEADER_SIZE = struct.calcsize(HEADER_FMT)
RECORD_FIXED_FMT = "<B B H I 8s I I"
RECORD_FIXED_SIZE = struct.calcsize(RECORD_FIXED_FMT)
assert RECORD_FIXED_SIZE == 24


def _emit_record(prev_ts_us: int, urb: Urb, fout) -> int:
    """Write one URB SUBMIT record. Returns the timestamp written (for the
    next iteration's inter-URB-gap computation)."""

    gap = max(0, urb.ts_us - prev_ts_us) if prev_ts_us else 0
    # cap at 1 second — the replay tool further caps at 100ms; this is just a
    # defensive guard so a multi-day pcap doesn't emit ridiculous values.
    gap = min(gap, 1_000_000)

    ep_with_dir = (urb.ep & 0x0F) | (0x80 if urb.dir_in else 0)
    setup = urb.setup if (urb.xfer_type == 2 and urb.setup) else b"\x00" * 8
    if len(setup) != 8:
        setup = (setup + b"\x00" * 8)[:8]
    # OUT submits carry payload bytes; IN submits get an empty on-disk data
    # area (the chip provides the bytes at replay time). transfer_length
    # tells the replay tool how big a buffer to allocate either way.
    if urb.dir_in:
        data = b""
        transfer_length = urb.length
    else:
        data = urb.payload or b""
        transfer_length = len(data)

    fout.write(struct.pack(
        RECORD_FIXED_FMT,
        urb.xfer_type, ep_with_dir, 0, gap, setup,
        transfer_length, len(data),
    ))
    fout.write(data)
    return urb.ts_us


def emit(
    urbs: list[Urb],
    out_path: Path,
    *,
    skip_in: bool = False,
) -> dict:
    """Walk the URB list, emit SUBMIT records to out_path. Returns stats."""

    stats = {
        "total_submits": 0,
        "ctrl_out": 0,
        "ctrl_in": 0,
        "bulk_out": 0,
        "bulk_in": 0,
        "intr_in": 0,
        "intr_out": 0,
        "skipped": 0,
    }

    submits = [u for u in urbs if u.event == "S"]
    # Skip ISO — not used by Realtek and the replay tool doesn't support it.
    submits = [u for u in submits if u.xfer_type != 0]

    # Optionally skip IN URBs (defensive — keep them by default).
    if skip_in:
        kept = []
        for u in submits:
            if u.dir_in and u.xfer_type in (1, 3):
                stats["skipped"] += 1
                continue
            kept.append(u)
        submits = kept

    # Reserve header space, write records, backpatch header with count.
    with open(out_path, "wb") as fout:
        fout.write(b"\x00" * HEADER_SIZE)
        prev_ts = 0
        for u in submits:
            prev_ts = _emit_record(prev_ts, u, fout)
            stats["total_submits"] += 1
            key = {
                (2, False): "ctrl_out", (2, True): "ctrl_in",
                (3, False): "bulk_out", (3, True): "bulk_in",
                (1, False): "intr_out", (1, True): "intr_in",
            }.get((u.xfer_type, u.dir_in))
            if key:
                stats[key] += 1
        # Backpatch real header.
        fout.seek(0)
        fout.write(struct.pack(HEADER_FMT, MAGIC, VERSION, stats["total_submits"]))
    return stats


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Convert a usbmon pcapng to a binary URB script for replay.",
    )
    p.add_argument("pcap", type=Path)
    p.add_argument("-o", "--output", type=Path, required=True)
    p.add_argument("--busnum", type=int, default=None,
                   help="Restrict to this USB bus.")
    p.add_argument("--devnum", type=int, default=None,
                   help="Restrict to this device address on the bus.")
    p.add_argument("--skip-in", action="store_true",
                   help="Drop interrupt/bulk IN URBs. Use only if you've "
                        "confirmed the chip doesn't act on C2H messages.")
    args = p.parse_args(argv)

    urbs = read_urbs(args.pcap, busnum=args.busnum, devnum=args.devnum)
    print(f"loaded {len(urbs)} URB events ({sum(1 for u in urbs if u.event == 'S')} submits)")
    stats = emit(urbs, args.output, skip_in=args.skip_in)
    print(f"wrote {stats['total_submits']} URB records to {args.output}")
    for k in ("ctrl_out", "ctrl_in", "bulk_out", "bulk_in", "intr_in", "intr_out"):
        if stats[k]:
            print(f"  {k}: {stats[k]}")
    if stats["skipped"]:
        print(f"  skipped (IN, --skip-in): {stats['skipped']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
