/* Auto-generated by tools/extract_8814a_phy_tables.py.
 * Source: aircrack-ng/rtl8814au v5.8.5.1. */

#ifndef HAL8814_PHYTABLES_H
#define HAL8814_PHYTABLES_H

#include "drv_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const u32 array_mp_8814a_agc_tab[];
extern const u32 array_mp_8814a_agc_tab_len;
extern const u32 array_mp_8814a_phy_reg[];
extern const u32 array_mp_8814a_phy_reg_len;
extern const u32 array_mp_8814a_phy_reg_mp[];
extern const u32 array_mp_8814a_phy_reg_mp_len;
extern const u32 array_mp_8814a_phy_reg_pg[];
extern const u32 array_mp_8814a_phy_reg_pg_len;
extern const u32 array_mp_8814a_phy_reg_pg_type0[];
extern const u32 array_mp_8814a_phy_reg_pg_type0_len;
extern const u32 array_mp_8814a_phy_reg_pg_type1[];
extern const u32 array_mp_8814a_phy_reg_pg_type1_len;
extern const u32 array_mp_8814a_phy_reg_pg_type10[];
extern const u32 array_mp_8814a_phy_reg_pg_type10_len;
extern const u32 array_mp_8814a_phy_reg_pg_type11[];
extern const u32 array_mp_8814a_phy_reg_pg_type11_len;
extern const u32 array_mp_8814a_phy_reg_pg_type2[];
extern const u32 array_mp_8814a_phy_reg_pg_type2_len;
extern const u32 array_mp_8814a_phy_reg_pg_type3[];
extern const u32 array_mp_8814a_phy_reg_pg_type3_len;
extern const u32 array_mp_8814a_phy_reg_pg_type4[];
extern const u32 array_mp_8814a_phy_reg_pg_type4_len;
extern const u32 array_mp_8814a_phy_reg_pg_type5[];
extern const u32 array_mp_8814a_phy_reg_pg_type5_len;
extern const u32 array_mp_8814a_phy_reg_pg_type6[];
extern const u32 array_mp_8814a_phy_reg_pg_type6_len;
extern const u32 array_mp_8814a_phy_reg_pg_type7[];
extern const u32 array_mp_8814a_phy_reg_pg_type7_len;
extern const u32 array_mp_8814a_phy_reg_pg_type8[];
extern const u32 array_mp_8814a_phy_reg_pg_type8_len;
extern const u32 array_mp_8814a_phy_reg_pg_type9[];
extern const u32 array_mp_8814a_phy_reg_pg_type9_len;
extern const u32 array_mp_8814a_mac_reg[];
extern const u32 array_mp_8814a_mac_reg_len;
extern const u32 array_mp_8814a_radioa[];
extern const u32 array_mp_8814a_radioa_len;
extern const u32 array_mp_8814a_radiob[];
extern const u32 array_mp_8814a_radiob_len;
extern const u32 array_mp_8814a_radioc[];
extern const u32 array_mp_8814a_radioc_len;
extern const u32 array_mp_8814a_radiod[];
extern const u32 array_mp_8814a_radiod_len;

#ifdef __cplusplus
}
#endif

#endif /* HAL8814_PHYTABLES_H */
